### ISSUE TITLE
Pomodoro timer inclusion?

### ISSUE THREAD

**Issue by endrebak** [afroisalreadyinu/gimme-cat#4]
I'd love to add a [pomodoro timer](http://en.wikipedia.org/wiki/Pomodoro_Technique) to `gimme-cat`, just two functions like `gimme-cat-catsup-start`, `gimme-cat-catsup-end` (for ending prematurely) that shows a cat picture after 25 mins. Would you accept such a PR?

**Comment by afroisalreadyinu** [comment]
Hehe, great idea. Go ahead, I would definitely accept it.

**Comment by endrebak** [comment]
Will need to learn about timers and such, but nice, will make an attempt.

**Comment by endrebak** [comment]
https://github.com/afroisalreadyinu/gimme-cat/pull/5

I am new to this, but seems to work and the code is very simple and easy to read I believe.

**Comment by endrebak** [comment]
Btw, I intend to add a few more bells and whistles; just need to use this for a while and see what I *really*  miss so I do not introduce unnecessary feature creep.
